### ISSUE TITLE
Version 0.13 not on flathub

### ISSUE THREAD

**Issue by liquidat** [flathub/org.freecol.FreeCol#10]
Commit https://github.com/flathub/org.freecol.FreeCol/commit/ad46d75502e870c9094fc24163692f56ee12e26c updated the code to version 0.13, however the version on flathub is currently still the old one:

```❯ flatpak info org.freecol.FreeCol

FreeCol - FreeCol a turn-based strategy game.

          ID: org.freecol.FreeCol
         Ref: app/org.freecol.FreeCol/x86_64/stable
        Arch: x86_64
      Branch: stable
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 276,3 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 27867e7401a3a0804a11247bbe25b92f4389b4451bc8966b208e3e9d0da7d7b6
      Parent: 575e1f423ad68820d33f890335f8c6c7c7358abf0474ecc5ff7893b3e4f582a7
     Subject: Use .tar.gz instead of .zip (ad46d755)
        Date: 2022-07-25 02:41:58 +0000
```

Any chance that we can push 0.13 out?

**Comment by hfiguiere** [comment]
did you flatpak update to update it?

**Comment by hfiguiere** [comment]
also this is the commit that include 0.13

**Comment by liquidat** [comment]
I did flatpak update. There is no update available. When I start freecol, it tells me it is version 0.12. Or am I missing something? 🤔 
![image](https://user-images.githubusercontent.com/1998084/181252643-e3ae04a6-9b41-4674-81e1-ccdf4b97cb08.png)

**Comment by hfiguiere** [comment]
that is could be upstream that show the wrong version?

**Comment by liquidat** [comment]
If I download the java installer from the web page, and start the game from there, it shows me the right version:

![image](https://user-images.githubusercontent.com/1998084/181296493-3d31089e-38af-4d53-aa3e-4623a11ccb71.png)

**Comment by hfiguiere** [comment]
0.13 is already there. Has always been. Just that the build process has been changed and require to set the version.

There was also an  undetected error in the metadata. All of this will be fixed soon.
