### ISSUE TITLE
FreeCol Flatpak is out of date - Flatpak version is 0.11.6, upstream is 0.13.0

### ISSUE THREAD

**Issue by dginovker** [flathub/org.freecol.FreeCol#7]
Upstream releases: https://github.com/FreeCol/freecol/releases

Originally reported on Flathub discourse: https://discourse.flathub.org/t/freecol-open-source-colonization-game-update-request-the-latest-build-from-2015/2730

**Comment by hfiguiere** [comment]
This was done with #8
